# Use the official MongoDB image
FROM mongo:latest

# Set environment variables for MongoDB
ENV MONGO_INITDB_DATABASE=cluster0

# Expose the default MongoDB port
EXPOSE 27017

# Command to run MongoDB
CMD ["mongod"]

